// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4OGhNLEbtRuVnar6eBO9RxwkTEbD4bXg',
    appId: '1:192372253036:web:358e6aa9c13091034ed349',
    messagingSenderId: '192372253036',
    projectId: 'programlama-cdb41',
    authDomain: 'programlama-cdb41.firebaseapp.com',
    storageBucket: 'programlama-cdb41.appspot.com',
    measurementId: 'G-SERCDGJBET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVO2YK0u30BdRCbESrpInSUTn43IH_oxs',
    appId: '1:192372253036:android:3a8d4dbbd2dce2a04ed349',
    messagingSenderId: '192372253036',
    projectId: 'programlama-cdb41',
    storageBucket: 'programlama-cdb41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKbgPUwaY29gNh9jdDYFLG0UypMc3hgA',
    appId: '1:192372253036:ios:b4d658ace074d1cf4ed349',
    messagingSenderId: '192372253036',
    projectId: 'programlama-cdb41',
    storageBucket: 'programlama-cdb41.appspot.com',
    iosBundleId: 'com.example.programlama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMKbgPUwaY29gNh9jdDYFLG0UypMc3hgA',
    appId: '1:192372253036:ios:d3b488826d6ac1ad4ed349',
    messagingSenderId: '192372253036',
    projectId: 'programlama-cdb41',
    storageBucket: 'programlama-cdb41.appspot.com',
    iosBundleId: 'com.example.programlama.RunnerTests',
  );
}
